name: Health Check

on:
  schedule:
    # - cron: '10 16,17,18 * * *'

jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://fso-part11-pokedex.onrender.com/health
      - name: Discord publish Health
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
          severity: info
          details: Health Check
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: Health Check
      - name: Discord publish Health
        uses: rjstone/discord-webhook-notify@v1
        if: failure()
        with:
          severity: error
          details: Health Check Failure !
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          text: Health Check Failure !

